### ISSUE TITLE
More help for JSON handling

### ISSUE THREAD

**Issue by TimGrt** [TimGrt/Ansible-Workshop-Exercises#105]
### Which section?

Projects

### Which sub-section?

Projects > Project - Network automation

### What is missing?

Attendees need more help with JSON handling in the last exercise of the Network automation project. It may help to write the output to a file for easier debugging:

```yaml
    - name: Write output to file for easier debugging, removing all keys with Ansible-specific content
      ansible.builtin.copy:
        content: "{{ common_contracts | ansible.utils.remove_keys(target=['changed', 'failed']) | to_nice_json }}"
        dest: "{{ playbook_dir }}/common-contracts.json"
        mode: "0644"
```
