### ISSUE TITLE
Change syntax and add variable to solution.

### ISSUE THREAD

**Issue by TimGrt** [TimGrt/Ansible-Workshop-Exercises#11]
https://github.com/TimGrt/Ansible-Workshop-Exercises/blob/c7b6846ae9eacbc33923e76f4cd600825ccc7952/docs/ansible-core/ansible-core-handlers.md?plain=1#L233

Better write it as:
```yaml
- name: Output {{ myuser }} info
  ansible.builtin.debug:
    msg: "{{ myuser }} uid: {{ getent_passwd[myuser][1] }}"
```
