### ISSUE TITLE
APIC project needs more info

### ISSUE THREAD

**Issue by TimGrt** [TimGrt/Ansible-Workshop-Exercises#54]
### Which section?

Projects

### Which sub-section?

Projects > Project - Network automation

### What is missing?

The Cisco ACI Sandbox Login changed slightly, the hostname differs, as well as the use_ssl parameter now is necessary.
With the following task connection is possible:
```yaml
- name: Query infos about APIC
  cisco.aci.aci_system:
     host: "{{ ansible_host }}"
     username: "{{ username }}"
     password: "{{ password }}"
     validate_certs: false
     use_ssl: true
     state: query
```

The inventory looks like this:
```ini
[apic]
sandboxapicdc.cisco.com
```
